[providers]
python = "3.11"

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[phases.build]
cmds = ["pip install -r requirements.txt"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"