"""Create initial tables

Revision ID: c2c51200b2da
Revises: 
Create Date: 2025-09-02 08:58:27.397588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c51200b2da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('influencers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('eldorado_username', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.Enum('users', 'cellphone', 'multiple', name='ownertype'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencers_eldorado_username'), 'influencers', ['eldorado_username'], unique=True)
    op.create_table('influencer_ids',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('eldorado_username', sa.String(length=100), nullable=False),
    sa.Column('tiktok_username', sa.String(length=100), nullable=True),
    sa.Column('tiktok_id', sa.String(length=255), nullable=True),
    sa.Column('instagram_username', sa.String(length=100), nullable=True),
    sa.Column('instagram_id', sa.String(length=255), nullable=True),
    sa.Column('facebook_username', sa.String(length=100), nullable=True),
    sa.Column('facebook_id', sa.String(length=255), nullable=True),
    sa.Column('x_username', sa.String(length=100), nullable=True),
    sa.Column('x_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['eldorado_username'], ['influencers.eldorado_username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eldorado_username')
    )
    op.create_table('partnerships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('eldorado_username', sa.String(length=100), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_videos', sa.Integer(), nullable=True),
    sa.Column('delivered_videos', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['eldorado_username'], ['influencers.eldorado_username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiktok_videos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('eldorado_username', sa.String(length=100), nullable=False),
    sa.Column('tiktok_username', sa.String(length=100), nullable=False),
    sa.Column('tiktok_video_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('public_video_url', sa.String(length=1000), nullable=True),
    sa.Column('watermark_free_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['eldorado_username'], ['influencers.eldorado_username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eldorado_username', 'tiktok_videos', ['eldorado_username'], unique=False)
    op.create_index('idx_likes', 'tiktok_videos', ['like_count'], unique=False)
    op.create_index('idx_published_date', 'tiktok_videos', ['published_at'], unique=False)
    op.create_index('idx_views', 'tiktok_videos', ['view_count'], unique=False)
    op.create_index(op.f('ix_tiktok_videos_tiktok_video_id'), 'tiktok_videos', ['tiktok_video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiktok_videos_tiktok_video_id'), table_name='tiktok_videos')
    op.drop_index('idx_views', table_name='tiktok_videos')
    op.drop_index('idx_published_date', table_name='tiktok_videos')
    op.drop_index('idx_likes', table_name='tiktok_videos')
    op.drop_index('idx_eldorado_username', table_name='tiktok_videos')
    op.drop_table('tiktok_videos')
    op.drop_table('partnerships')
    op.drop_table('influencer_ids')
    op.drop_index(op.f('ix_influencers_eldorado_username'), table_name='influencers')
    op.drop_table('influencers')
    op.drop_table('campaigns')
    # ### end Alembic commands ###