"""Add transcription column to tiktok_videos

Revision ID: dbf407b8a5a5
Revises: a1b2c3d4e5f6
Create Date: 2025-09-03 06:36:56.263333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf407b8a5a5'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('influencers', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'influencers', 'owners', ['owner_id'], ['id'])
    op.add_column('tiktok_videos', sa.Column('transcription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiktok_videos', 'transcription')
    op.drop_constraint(None, 'influencers', type_='foreignkey')
    op.drop_column('influencers', 'owner_id')
    op.drop_table('owners')
    # ### end Alembic commands ###